# Generated by Django 3.2.7 on 2021-09-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_desi', models.CharField(max_length=200)),
                ('rm1', models.CharField(max_length=200)),
                ('rm2', models.CharField(max_length=200)),
                ('rm3', models.CharField(max_length=200)),
                ('process', models.CharField(max_length=300)),
            ],
        ),
    ]
