# Generated by Django 4.0.2 on 2022-03-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, null=True)),
                ('emp_name', models.CharField(max_length=50, null=True)),
                ('team', models.CharField(max_length=50, null=True)),
                ('pl_balance', models.IntegerField()),
                ('sl_balance', models.IntegerField()),
                ('present_count', models.IntegerField(default=0)),
            ],
        ),
    ]
