# Generated by Django 3.2.7 on 2021-09-03 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_alter_attendace_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendace',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
