# Generated by Django 3.2.7 on 2021-09-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0006_alter_attendace_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendace',
            name='attendance_type',
            field=models.CharField(default='Unmarked', max_length=100),
        ),
    ]
