# Generated by Django 4.0.2 on 2022-02-24 06:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=200, null=True)),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_desi', models.CharField(max_length=200)),
                ('emp_rm1', models.CharField(max_length=200)),
                ('emp_rm2', models.CharField(max_length=200)),
                ('emp_rm3', models.CharField(max_length=200)),
                ('emp_process', models.CharField(max_length=200)),
                ('id_extra', models.IntegerField(null=True)),
                ('on_id', models.IntegerField(blank=True, null=True)),
                ('agent_status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MappingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('updated_by', models.CharField(max_length=50)),
                ('emp_name', models.CharField(max_length=50, null=True)),
                ('emp_id', models.IntegerField(null=True)),
                ('rm1', models.CharField(max_length=50, null=True)),
                ('rm2', models.CharField(max_length=50, null=True)),
                ('rm3', models.CharField(max_length=50, null=True)),
                ('team', models.CharField(max_length=100, null=True)),
                ('history', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MappingHistoryTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('updated_by', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50)),
                ('new_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100, null=True)),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_desi', models.CharField(max_length=200)),
                ('emp_rm1', models.CharField(max_length=200)),
                ('emp_rm2', models.CharField(max_length=200)),
                ('emp_rm3', models.CharField(max_length=200)),
                ('emp_process', models.CharField(max_length=200)),
                ('extra_id', models.IntegerField(default=1)),
                ('pc', models.BooleanField(default=False)),
                ('img', models.ImageField(default='users/default.png', upload_to='users/')),
                ('doj', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('on_id', models.IntegerField(blank=True, null=True)),
                ('agent_status', models.CharField(default='Active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
