# Generated by Django 4.0.2 on 2022-02-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id_extra',
        ),
    ]
