# Generated by Django 4.0.2 on 2022-02-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_remove_employee_id_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_extra',
            field=models.IntegerField(null=True),
        ),
    ]
