# Generated by Django 4.0.2 on 2022-02-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_employee_id_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='extra_id',
        ),
    ]
