# Generated by Django 4.0.2 on 2022-02-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_remove_profile_extra_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='doj',
        ),
    ]
