# Generated by Django 4.0.2 on 2022-02-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0005_remove_profile_doj'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
    ]
