# Generated by Django 4.0.2 on 2022-02-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0006_profile_doj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='on_id',
        ),
    ]
