# Generated by Django 4.0.2 on 2022-02-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0007_remove_employee_on_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='on_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
